insert into district (city_id, name) values
(1,'Aladağ'),
(1,'Ceyhan'),
(1,'Çukurova'),
(1,'Feke'),
(1,'İmamoğlu'),
(1,'Karaisalı'),
(1,'Karataş'),
(1,'Kozan'),
(1,'Pozantı'),
(1,'Saimbeyli'),
(1,'Sarıçam'),
(1,'Seyhan'),
(1,'Tufanbeyli'),
(1,'Yumurtalık'),
(1,'Yüreğir');